apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strapi-sync-wizard.fullname" . }}
  labels:
    {{- include "strapi-sync-wizard.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.database.existingSecret.enabled }}
  database-username: {{ include "strapi-sync-wizard.databaseUsername" . | b64enc | quote }}
  database-password: {{ include "strapi-sync-wizard.databasePassword" . | b64enc | quote }}
  {{- end }}
  database-salt: {{ .Values.database.salt | default "" | b64enc | quote }}